run: ppo
stop:
  training_iteration: 500
custom_metrics:
- cstr_viol
postproc_data:
  episode_step_data: 
  - x
  - h
  - u
  - v
  - m
  - t
  - Tx
  - Th
  episode_end_data: 
  - xf
  - hf
  - uf
  - vf
  - mf
num_eval_episodes: 100
eval_env_config:
  env_config:
    prng_seed: 0
config:
  num_workers: 7
  num_envs_per_worker: 10
  num_gpus: 0
  num_cpus_per_worker: 1
  num_gpus_per_worker: 0
  num_cpus_for_driver: 1
  rollout_fragment_length: 40
  batch_mode: complete_episodes
  train_batch_size: 2800
  model:
    fcnet_hiddens: [64, 64]
    fcnet_activation: tanh
    vf_share_layers: False
    free_log_std: True
  gamma: 1.
  log_level: INFO
  framework: tf
  explore: True
  ignore_worker_failures: True
  evaluation_interval: 1
  evaluation_num_episodes: 400
  evaluation_config:
    explore: False
  evaluation_num_workers: 0
  use_critic: True
  use_gae: True
  lambda: 1.
  kl_coeff: 0.
  sgd_minibatch_size: 280
  shuffle_sequences: True
  num_sgd_iter: 10
  lr: 1.0e-04
  vf_loss_coeff: 0.5
  clip_param: 0.2
  callbacks:
    TrainingCallbacks
  env: environment.landing2d.Landing2DEnv
  env_config:
    H: 40
    x0_min: -0.38
    x0_max: 0.38
    h0_min: 0.8
    h0_max: 1.2
    u0_min: -0.98
    u0_max: 0.98
    v0_min: -0.083
    v0_max: -1.917
    m0: 1.0
    tf: 0.106
    xf: 0.0
    hf: 0.0
    uf: 0.0
    vf: 0.0
    Tmax: 2.55
    c: 1.89
    g: 1.0
   
